<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BlankDemandPlanner.Core\BlankDemandPlanner.Core.csproj" />
    <ProjectReference Include="..\BlankDemandPlanner.Data\BlankDemandPlanner.Data.csproj" />
    <ProjectReference Include="..\BlankDemandPlanner.Services\BlankDemandPlanner.Services.csproj" />
    <ProjectReference Include="..\BlankDemandPlanner.Infrastructure\BlankDemandPlanner.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\pzmc-logo.png" />
    <Resource Include="Assets\pzmc-symbol.png" />
    <Resource Include="Assets\pzmc-logo-black-transparent.png" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
